name = "flappy-bird"
main = "src/server/index.ts"
compatibility_date = "2024-12-30"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "flappy-bird-db"
database_id = "f2cd90dd-6acc-418b-a0e1-c345614c412b"
migrations_dir = "migrations"
